### ISSUE TITLE
Error locationCity

### ISSUE THREAD

**Issue by lvinoeserdce** [fabiocaccamo/FCIPAddressGeocoder#6]
Hi! I tried to get locationCity after getting geocode, but I got undefined error
![2016-11-25 21 16 48](https://cloud.githubusercontent.com/assets/11653316/20633447/a7ff2f36-b357-11e6-83e2-ac75883681bb.png)

Here is my translate function, but I think that is not the case
```
public static func translate(s: String) -> String {
        var result = s.lowercaseString
        let replace: ((String, String) -> Void) = { (eng, rus) in
            result = result.stringByReplacingOccurrencesOfString(eng, withString: rus)
        }
        triples.forEach(replace)
        doubles.forEach(replace)
        if useUmlauts {
            result = result.stringByReplacingOccurrencesOfString("е", withString: "ё")
        }
        pairs.forEach(replace)
        return result
}
```

If it possible help me please

**Comment by fabiocaccamo** [comment]
It is not sure that a `locationCity` will be available after geocoding, just check if `locationCity` is defined or not before doing stuff depending on it.

**Comment by lvinoeserdce** [comment]
@fabiocaccamo my coordinates: lat 58.603532, lon 49.666798

**Comment by fabiocaccamo** [comment]
@lvinoeserdce sorry, could you give me your device ip address?

This library actually supports 4 different geo-ip services, you can change the default one and try to repeat the test.

```
[FCIPAddressGeocoder setDefaultService:FCIPAddressGeocoderServiceFreeGeoIP];
//repeat the test

[FCIPAddressGeocoder setDefaultService:FCIPAddressGeocoderServicePetabyet];
//repeat the test

[FCIPAddressGeocoder setDefaultService:FCIPAddressGeocoderServiceSmartIP];
//repeat the test

[FCIPAddressGeocoder setDefaultService:FCIPAddressGeocoderServiceTelize];
//repeat the test
```

**Comment by lvinoeserdce** [comment]
@fabiocaccamo Your previous reply helped me, thank you!
